package leetcode

object Tags {
  trait Easy
  trait Medium
  trait Hard

  trait Amazon
  trait Google
  trait Facebook
  trait Microsoft
  trait Twitter
  trait Apple
  trait Oracle
  trait VMware
  trait Paypal
  trait Cisco
  trait Adobe
  trait Bloomberg
  trait Uber
  trait LinedIn
  trait Yahoo
  trait Alibaba
  trait Tencent
  trait Airbnb
  trait Snapchat
  trait Pinterest
  trait Baidu
  trait Visa
  trait Hulu
  trait SAP
  trait Dropbox
  trait Samsung
  trait Yandex
  trait Square
  trait Quora
  trait Intel
  trait JPMorgan
  trait Databricks
  trait Yelp
  trait EBay
  trait IBM
  trait DiDi
  trait Netflix
  trait Reddit

  trait TopicArray
  trait TopicDynamicProgramming
  trait TopicMath
  trait TopicString
  trait TopicTree
  trait TopicHashTable
  trait TopicDFS
  trait TopicBinarySearch
  trait TopicTwoPointers
  trait TopicGreedy
  trait TopicBFS
  trait TopicStack
  trait TopicBacktracking
  trait TopicDesign
  trait TopicLinkedList
  trait TopicBitManipulation
  trait TopicHeap
  trait TopicSort
  trait TopicGraph
  trait TopicUnionFind
  trait TopicDivideAndConquer
  trait TopicTrie
  trait TopicRecursion
  trait TopicSlidingWindow
  trait TopicOrderedMap
  trait TopicSegmentTree
  trait TopicQueue
  trait TopicMinimax
  trait TopicBinaryIndexedTree
  trait TopicRandom
  trait TopicTopologicalSort
  trait TopicBraineaser
  trait TopicGeometry
  trait TopicLineSweep
  trait TopicRejectionSampling
  trait TopicReservoirSampling
  trait TopicBinarySearchTree
  trait TopicMemoization
}
